### ISSUE TITLE
fix off-chain signature validation

### ISSUE THREAD

**Issue by NiloCK** [statechannels/SCBridge-Wallet#112]
recoverSigner attempts are now skipped - some massaging of inputs should fix this.

**Comment by geoknee** [comment]
For example here https://github.com/statechannels/nitro-smart-contract-wallet/blob/c4ef557bbff3271d80c99155ba2f63484567aa0c/clients/OwnerClient.ts#L70 

We probably want to write a test to exercise this logic and reproduce the bug, since getting there manually isn't straightforward on `main` just now.
